### ISSUE TITLE
Is it work?

### ISSUE THREAD

**Issue by Praying** [wdkGitHub/RainbowBracketsCrack#1]
is it works for the latest Rainbow Brackets version:  2023.3.9-233?

**Comment by wdkGitHub** [comment]
try

**Comment by Praying** [comment]
it seems not work, my machine is the macbook pro m1. does it works on x86_64 machine?

**Comment by wdkGitHub** [comment]
ja-netfilter-all can be used, this should work, M series chips have not been tested.

**Comment by Praying** [comment]
I used je-netfilter  in hardbin.com, is it different from ja-netfilter-all ?

**Comment by wdkGitHub** [comment]
the same ， https://3.jetbra.in/

**Comment by Praying** [comment]
I also tried in Ubuntu (x64)， it also not work

**Comment by wdkGitHub** [comment]
[RainbowBracketsCrackPlugin-1.0.5.jar.zip](https://github.com/wdkGitHub/RainbowBracketsCrack/files/14003534/RainbowBracketsCrackPlugin-1.0.5.jar.zip)

**Comment by wdkGitHub** [comment]
> I also tried in Ubuntu (x64)， it also not work

It has nothing to do with the operating system

**Comment by Praying** [comment]
I tries 1.0.7 jar and It Works!!! God Job. Thanks so much!

**Comment by wdkGitHub** [comment]
Supports fastrequest plugin
